//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartbeatMenu.Adapters
{
    
    public class IModuleAssemblyContractToViewAddInAdapter : StartbeatMenu.Views.IModuleAssembly
    {
        private Start9.Api.Contracts.IModuleAssemblyContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IModuleAssemblyContractToViewAddInAdapter()
        {
        }
        public IModuleAssemblyContractToViewAddInAdapter(Start9.Api.Contracts.IModuleAssemblyContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public string Name
        {
            get
            {
                return _contract.Name;
            }
        }
        public string Description
        {
            get
            {
                return _contract.Description;
            }
        }
        public string Publisher
        {
            get
            {
                return _contract.Publisher;
            }
        }
        public System.Version Version
        {
            get
            {
                return _contract.Version;
            }
        }
        public System.Collections.Generic.IList<StartbeatMenu.Views.IModuleInstance> Instances
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IModuleInstanceContract, StartbeatMenu.Views.IModuleInstance>(_contract.Instances, StartbeatMenu.Adapters.IModuleInstanceAddInAdapter.ContractToViewAdapter, StartbeatMenu.Adapters.IModuleInstanceAddInAdapter.ViewToContractAdapter);
            }
        }
        public StartbeatMenu.Views.IConfiguration SavedConfiguration
        {
            get
            {
                return StartbeatMenu.Adapters.IConfigurationAddInAdapter.ContractToViewAdapter(_contract.SavedConfiguration);
            }
        }
        public StartbeatMenu.Views.IConfiguration CurrentConfiguration
        {
            get
            {
                return StartbeatMenu.Adapters.IConfigurationAddInAdapter.ContractToViewAdapter(_contract.CurrentConfiguration);
            }
        }
        public StartbeatMenu.Views.IMessageContract MessageContract
        {
            get
            {
                return StartbeatMenu.Adapters.IMessageContractAddInAdapter.ContractToViewAdapter(_contract.MessageContract);
            }
        }
        public StartbeatMenu.Views.IReceiverContract ReceiverContract
        {
            get
            {
                return StartbeatMenu.Adapters.IReceiverContractAddInAdapter.ContractToViewAdapter(_contract.ReceiverContract);
            }
        }
        public void Kill(StartbeatMenu.Views.IModuleInstance instance)
        {
            _contract.Kill(StartbeatMenu.Adapters.IModuleInstanceAddInAdapter.ViewToContractAdapter(instance));
        }
        public void KillAll()
        {
            _contract.KillAll();
        }
        public void Activate(bool initialize)
        {
            _contract.Activate(initialize);
        }
        internal Start9.Api.Contracts.IModuleAssemblyContract GetSourceContract()
        {
            return _contract;
        }
    }
}

